// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package category

import (
	"errors"
	"fmt"
)

const (
	// TypeIncome is a Type of type income.
	TypeIncome Type = "income"
	// TypeExpense is a Type of type expense.
	TypeExpense Type = "expense"
)

var ErrInvalidType = errors.New("not a valid Type")

// String implements the Stringer interface.
func (x Type) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, err := ParseType(string(x))
	return err == nil
}

var _TypeValue = map[string]Type{
	"income":  TypeIncome,
	"expense": TypeExpense,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(""), fmt.Errorf("%s is %w", name, ErrInvalidType)
}
