// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package transaction

import (
	"errors"
	"fmt"
)

const (
	// TypeIncome is a Type of type Income.
	TypeIncome Type = iota
	// TypeExpense is a Type of type Expense.
	TypeExpense
)

var ErrInvalidType = errors.New("not a valid Type")

const _TypeName = "incomeexpense"

var _TypeMap = map[Type]string{
	TypeIncome:  _TypeName[0:6],
	TypeExpense: _TypeName[6:13],
}

// String implements the Stringer interface.
func (x Type) String() string {
	if str, ok := _TypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Type(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, ok := _TypeMap[x]
	return ok
}

var _TypeValue = map[string]Type{
	_TypeName[0:6]:  TypeIncome,
	_TypeName[6:13]: TypeExpense,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(0), fmt.Errorf("%s is %w", name, ErrInvalidType)
}
