// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/Nemizar/coin_tamer_bot/internal/core/domain/models/category"
	"github.com/Nemizar/coin_tamer_bot/internal/core/domain/models/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewCategoryRepositoryMock creates a new instance of CategoryRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepositoryMock {
	mock := &CategoryRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryRepositoryMock is an autogenerated mock type for the CategoryRepository type
type CategoryRepositoryMock struct {
	mock.Mock
}

type CategoryRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepositoryMock) EXPECT() *CategoryRepositoryMock_Expecter {
	return &CategoryRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CategoryRepositoryMock
func (_mock *CategoryRepositoryMock) Create(ctx context.Context, category1 *category.Category) error {
	ret := _mock.Called(ctx, category1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *category.Category) error); ok {
		r0 = returnFunc(ctx, category1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category1 *category.Category
func (_e *CategoryRepositoryMock_Expecter) Create(ctx interface{}, category1 interface{}) *CategoryRepositoryMock_Create_Call {
	return &CategoryRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, category1)}
}

func (_c *CategoryRepositoryMock_Create_Call) Run(run func(ctx context.Context, category1 *category.Category)) *CategoryRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *category.Category
		if args[1] != nil {
			arg1 = args[1].(*category.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepositoryMock_Create_Call) Return(err error) *CategoryRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, category1 *category.Category) error) *CategoryRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseByUserID provides a mock function for the type CategoryRepositoryMock
func (_mock *CategoryRepositoryMock) GetExpenseByUserID(ctx context.Context, userID shared.ID) ([]*category.Category, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseByUserID")
	}

	var r0 []*category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) ([]*category.Category, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) []*category.Category); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepositoryMock_GetExpenseByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseByUserID'
type CategoryRepositoryMock_GetExpenseByUserID_Call struct {
	*mock.Call
}

// GetExpenseByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID shared.ID
func (_e *CategoryRepositoryMock_Expecter) GetExpenseByUserID(ctx interface{}, userID interface{}) *CategoryRepositoryMock_GetExpenseByUserID_Call {
	return &CategoryRepositoryMock_GetExpenseByUserID_Call{Call: _e.mock.On("GetExpenseByUserID", ctx, userID)}
}

func (_c *CategoryRepositoryMock_GetExpenseByUserID_Call) Run(run func(ctx context.Context, userID shared.ID)) *CategoryRepositoryMock_GetExpenseByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.ID
		if args[1] != nil {
			arg1 = args[1].(shared.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepositoryMock_GetExpenseByUserID_Call) Return(categorys []*category.Category, err error) *CategoryRepositoryMock_GetExpenseByUserID_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryRepositoryMock_GetExpenseByUserID_Call) RunAndReturn(run func(ctx context.Context, userID shared.ID) ([]*category.Category, error)) *CategoryRepositoryMock_GetExpenseByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetIncomeByUserID provides a mock function for the type CategoryRepositoryMock
func (_mock *CategoryRepositoryMock) GetIncomeByUserID(ctx context.Context, userID shared.ID) ([]*category.Category, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetIncomeByUserID")
	}

	var r0 []*category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) ([]*category.Category, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) []*category.Category); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepositoryMock_GetIncomeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIncomeByUserID'
type CategoryRepositoryMock_GetIncomeByUserID_Call struct {
	*mock.Call
}

// GetIncomeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID shared.ID
func (_e *CategoryRepositoryMock_Expecter) GetIncomeByUserID(ctx interface{}, userID interface{}) *CategoryRepositoryMock_GetIncomeByUserID_Call {
	return &CategoryRepositoryMock_GetIncomeByUserID_Call{Call: _e.mock.On("GetIncomeByUserID", ctx, userID)}
}

func (_c *CategoryRepositoryMock_GetIncomeByUserID_Call) Run(run func(ctx context.Context, userID shared.ID)) *CategoryRepositoryMock_GetIncomeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.ID
		if args[1] != nil {
			arg1 = args[1].(shared.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepositoryMock_GetIncomeByUserID_Call) Return(categorys []*category.Category, err error) *CategoryRepositoryMock_GetIncomeByUserID_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryRepositoryMock_GetIncomeByUserID_Call) RunAndReturn(run func(ctx context.Context, userID shared.ID) ([]*category.Category, error)) *CategoryRepositoryMock_GetIncomeByUserID_Call {
	_c.Call.Return(run)
	return _c
}
