// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/Nemizar/coin_tamer_bot/internal/core/domain/models/shared"
	"github.com/Nemizar/coin_tamer_bot/internal/core/domain/models/transaction"
	mock "github.com/stretchr/testify/mock"
)

// NewTransactionRepositoryMock creates a new instance of TransactionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepositoryMock {
	mock := &TransactionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionRepositoryMock is an autogenerated mock type for the TransactionRepository type
type TransactionRepositoryMock struct {
	mock.Mock
}

type TransactionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepositoryMock) EXPECT() *TransactionRepositoryMock_Expecter {
	return &TransactionRepositoryMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type TransactionRepositoryMock
func (_mock *TransactionRepositoryMock) Add(ctx context.Context, transaction1 *transaction.Transaction) error {
	ret := _mock.Called(ctx, transaction1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepositoryMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type TransactionRepositoryMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction1 *transaction.Transaction
func (_e *TransactionRepositoryMock_Expecter) Add(ctx interface{}, transaction1 interface{}) *TransactionRepositoryMock_Add_Call {
	return &TransactionRepositoryMock_Add_Call{Call: _e.mock.On("Add", ctx, transaction1)}
}

func (_c *TransactionRepositoryMock_Add_Call) Run(run func(ctx context.Context, transaction1 *transaction.Transaction)) *TransactionRepositoryMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transaction.Transaction
		if args[1] != nil {
			arg1 = args[1].(*transaction.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepositoryMock_Add_Call) Return(err error) *TransactionRepositoryMock_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepositoryMock_Add_Call) RunAndReturn(run func(ctx context.Context, transaction1 *transaction.Transaction) error) *TransactionRepositoryMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TransactionRepositoryMock
func (_mock *TransactionRepositoryMock) Delete(ctx context.Context, id shared.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TransactionRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id shared.ID
func (_e *TransactionRepositoryMock_Expecter) Delete(ctx interface{}, id interface{}) *TransactionRepositoryMock_Delete_Call {
	return &TransactionRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TransactionRepositoryMock_Delete_Call) Run(run func(ctx context.Context, id shared.ID)) *TransactionRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.ID
		if args[1] != nil {
			arg1 = args[1].(shared.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepositoryMock_Delete_Call) Return(err error) *TransactionRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id shared.ID) error) *TransactionRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TransactionRepositoryMock
func (_mock *TransactionRepositoryMock) Get(ctx context.Context, id shared.ID) (*transaction.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *transaction.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) (*transaction.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.ID) *transaction.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TransactionRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TransactionRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id shared.ID
func (_e *TransactionRepositoryMock_Expecter) Get(ctx interface{}, id interface{}) *TransactionRepositoryMock_Get_Call {
	return &TransactionRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *TransactionRepositoryMock_Get_Call) Run(run func(ctx context.Context, id shared.ID)) *TransactionRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.ID
		if args[1] != nil {
			arg1 = args[1].(shared.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepositoryMock_Get_Call) Return(transaction1 *transaction.Transaction, err error) *TransactionRepositoryMock_Get_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *TransactionRepositoryMock_Get_Call) RunAndReturn(run func(ctx context.Context, id shared.ID) (*transaction.Transaction, error)) *TransactionRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TransactionRepositoryMock
func (_mock *TransactionRepositoryMock) Update(ctx context.Context, transaction1 *transaction.Transaction) error {
	ret := _mock.Called(ctx, transaction1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TransactionRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction1 *transaction.Transaction
func (_e *TransactionRepositoryMock_Expecter) Update(ctx interface{}, transaction1 interface{}) *TransactionRepositoryMock_Update_Call {
	return &TransactionRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, transaction1)}
}

func (_c *TransactionRepositoryMock_Update_Call) Run(run func(ctx context.Context, transaction1 *transaction.Transaction)) *TransactionRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transaction.Transaction
		if args[1] != nil {
			arg1 = args[1].(*transaction.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TransactionRepositoryMock_Update_Call) Return(err error) *TransactionRepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, transaction1 *transaction.Transaction) error) *TransactionRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
