// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/Nemizar/coin_tamer_bot/internal/core/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewUnitOfWorkMock creates a new instance of UnitOfWorkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWorkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWorkMock {
	mock := &UnitOfWorkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnitOfWorkMock is an autogenerated mock type for the UnitOfWork type
type UnitOfWorkMock struct {
	mock.Mock
}

type UnitOfWorkMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitOfWorkMock) EXPECT() *UnitOfWorkMock_Expecter {
	return &UnitOfWorkMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) Begin(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UnitOfWorkMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type UnitOfWorkMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnitOfWorkMock_Expecter) Begin(ctx interface{}) *UnitOfWorkMock_Begin_Call {
	return &UnitOfWorkMock_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *UnitOfWorkMock_Begin_Call) Run(run func(ctx context.Context)) *UnitOfWorkMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UnitOfWorkMock_Begin_Call) Return(err error) *UnitOfWorkMock_Begin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UnitOfWorkMock_Begin_Call) RunAndReturn(run func(ctx context.Context) error) *UnitOfWorkMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// CategoryRepository provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) CategoryRepository() ports.CategoryRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CategoryRepository")
	}

	var r0 ports.CategoryRepository
	if returnFunc, ok := ret.Get(0).(func() ports.CategoryRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.CategoryRepository)
		}
	}
	return r0
}

// UnitOfWorkMock_CategoryRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CategoryRepository'
type UnitOfWorkMock_CategoryRepository_Call struct {
	*mock.Call
}

// CategoryRepository is a helper method to define mock.On call
func (_e *UnitOfWorkMock_Expecter) CategoryRepository() *UnitOfWorkMock_CategoryRepository_Call {
	return &UnitOfWorkMock_CategoryRepository_Call{Call: _e.mock.On("CategoryRepository")}
}

func (_c *UnitOfWorkMock_CategoryRepository_Call) Run(run func()) *UnitOfWorkMock_CategoryRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnitOfWorkMock_CategoryRepository_Call) Return(categoryRepository ports.CategoryRepository) *UnitOfWorkMock_CategoryRepository_Call {
	_c.Call.Return(categoryRepository)
	return _c
}

func (_c *UnitOfWorkMock_CategoryRepository_Call) RunAndReturn(run func() ports.CategoryRepository) *UnitOfWorkMock_CategoryRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UnitOfWorkMock_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type UnitOfWorkMock_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UnitOfWorkMock_Expecter) Commit(ctx interface{}) *UnitOfWorkMock_Commit_Call {
	return &UnitOfWorkMock_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *UnitOfWorkMock_Commit_Call) Run(run func(ctx context.Context)) *UnitOfWorkMock_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UnitOfWorkMock_Commit_Call) Return(err error) *UnitOfWorkMock_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UnitOfWorkMock_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *UnitOfWorkMock_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) Logger() ports.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 ports.Logger
	if returnFunc, ok := ret.Get(0).(func() ports.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.Logger)
		}
	}
	return r0
}

// UnitOfWorkMock_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type UnitOfWorkMock_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *UnitOfWorkMock_Expecter) Logger() *UnitOfWorkMock_Logger_Call {
	return &UnitOfWorkMock_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *UnitOfWorkMock_Logger_Call) Run(run func()) *UnitOfWorkMock_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnitOfWorkMock_Logger_Call) Return(logger ports.Logger) *UnitOfWorkMock_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *UnitOfWorkMock_Logger_Call) RunAndReturn(run func() ports.Logger) *UnitOfWorkMock_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackUnlessCommitted provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) RollbackUnlessCommitted() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RollbackUnlessCommitted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UnitOfWorkMock_RollbackUnlessCommitted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackUnlessCommitted'
type UnitOfWorkMock_RollbackUnlessCommitted_Call struct {
	*mock.Call
}

// RollbackUnlessCommitted is a helper method to define mock.On call
func (_e *UnitOfWorkMock_Expecter) RollbackUnlessCommitted() *UnitOfWorkMock_RollbackUnlessCommitted_Call {
	return &UnitOfWorkMock_RollbackUnlessCommitted_Call{Call: _e.mock.On("RollbackUnlessCommitted")}
}

func (_c *UnitOfWorkMock_RollbackUnlessCommitted_Call) Run(run func()) *UnitOfWorkMock_RollbackUnlessCommitted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnitOfWorkMock_RollbackUnlessCommitted_Call) Return(err error) *UnitOfWorkMock_RollbackUnlessCommitted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UnitOfWorkMock_RollbackUnlessCommitted_Call) RunAndReturn(run func() error) *UnitOfWorkMock_RollbackUnlessCommitted_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionRepository provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) TransactionRepository() ports.TransactionRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TransactionRepository")
	}

	var r0 ports.TransactionRepository
	if returnFunc, ok := ret.Get(0).(func() ports.TransactionRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.TransactionRepository)
		}
	}
	return r0
}

// UnitOfWorkMock_TransactionRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionRepository'
type UnitOfWorkMock_TransactionRepository_Call struct {
	*mock.Call
}

// TransactionRepository is a helper method to define mock.On call
func (_e *UnitOfWorkMock_Expecter) TransactionRepository() *UnitOfWorkMock_TransactionRepository_Call {
	return &UnitOfWorkMock_TransactionRepository_Call{Call: _e.mock.On("TransactionRepository")}
}

func (_c *UnitOfWorkMock_TransactionRepository_Call) Run(run func()) *UnitOfWorkMock_TransactionRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnitOfWorkMock_TransactionRepository_Call) Return(transactionRepository ports.TransactionRepository) *UnitOfWorkMock_TransactionRepository_Call {
	_c.Call.Return(transactionRepository)
	return _c
}

func (_c *UnitOfWorkMock_TransactionRepository_Call) RunAndReturn(run func() ports.TransactionRepository) *UnitOfWorkMock_TransactionRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type UnitOfWorkMock
func (_mock *UnitOfWorkMock) UserRepository() ports.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 ports.UserRepository
	if returnFunc, ok := ret.Get(0).(func() ports.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.UserRepository)
		}
	}
	return r0
}

// UnitOfWorkMock_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type UnitOfWorkMock_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *UnitOfWorkMock_Expecter) UserRepository() *UnitOfWorkMock_UserRepository_Call {
	return &UnitOfWorkMock_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *UnitOfWorkMock_UserRepository_Call) Run(run func()) *UnitOfWorkMock_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnitOfWorkMock_UserRepository_Call) Return(userRepository ports.UserRepository) *UnitOfWorkMock_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *UnitOfWorkMock_UserRepository_Call) RunAndReturn(run func() ports.UserRepository) *UnitOfWorkMock_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
