// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portsmocks

import (
	"context"

	"github.com/Nemizar/coin_tamer_bot/internal/core/domain/models/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) Create(ctx context.Context, user1 *user.User) error {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *UserRepositoryMock_Expecter) Create(ctx interface{}, user1 interface{}) *UserRepositoryMock_Create_Call {
	return &UserRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, user1)}
}

func (_c *UserRepositoryMock_Create_Call) Run(run func(ctx context.Context, user1 *user.User)) *UserRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_Create_Call) Return(err error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByExternalProvider provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) FindByExternalProvider(ctx context.Context, provider user.Provider, externalID string) (*user.User, error) {
	ret := _mock.Called(ctx, provider, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalProvider")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Provider, string) (*user.User, error)); ok {
		return returnFunc(ctx, provider, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Provider, string) *user.User); ok {
		r0 = returnFunc(ctx, provider, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.Provider, string) error); ok {
		r1 = returnFunc(ctx, provider, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_FindByExternalProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByExternalProvider'
type UserRepositoryMock_FindByExternalProvider_Call struct {
	*mock.Call
}

// FindByExternalProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider user.Provider
//   - externalID string
func (_e *UserRepositoryMock_Expecter) FindByExternalProvider(ctx interface{}, provider interface{}, externalID interface{}) *UserRepositoryMock_FindByExternalProvider_Call {
	return &UserRepositoryMock_FindByExternalProvider_Call{Call: _e.mock.On("FindByExternalProvider", ctx, provider, externalID)}
}

func (_c *UserRepositoryMock_FindByExternalProvider_Call) Run(run func(ctx context.Context, provider user.Provider, externalID string)) *UserRepositoryMock_FindByExternalProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Provider
		if args[1] != nil {
			arg1 = args[1].(user.Provider)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_FindByExternalProvider_Call) Return(user1 *user.User, err error) *UserRepositoryMock_FindByExternalProvider_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepositoryMock_FindByExternalProvider_Call) RunAndReturn(run func(ctx context.Context, provider user.Provider, externalID string) (*user.User, error)) *UserRepositoryMock_FindByExternalProvider_Call {
	_c.Call.Return(run)
	return _c
}
